### PR TITLE
Create temporary file with Google credential for terraformcloud

### PR DESCRIPTION
**Pull request by felipe-minka**
This includes the following PR and the requested changes
https://github.com/cyrilgdn/terraform-provider-postgresql/pull/180

### CODE REVIEW

**Comment by chris-minka** [comment]
Hi @cyrilgdn. Any chance we could get this merged? It fixes #138.

Also, thank you for creating this provider!

**Comment by Klaitos** [comment]
Definitively need this one to be merged too !

**Comment by cyrilgdn** [comment]
Hi @felipe-minka , 

Sorry I was off the project for a while; thanks a lot  for the PR :+1: 

Could you just merge master so it will trigger the tests again (normally I'm able to trigger them directly on the PR but I don't know why the button does not appear here :thinking: )

I tried, but don't have the right to push on your branch.

**Comment by chris-minka** [comment]
Hi @cyrilgdn. We are glad you are back! I had permissions to merge master so it is done now and awaiting workflow approval. FYI @felipe-minka.

**Review by cyrilgdn — APPROVED** [review]
Many thanks :+1:

**Comment by adamlc** [comment]
Thanks for this, just come across the same problem in Terraform Cloud. Looking forward to the official release :)

**Comment by cyrilgdn** [comment]
This has been released in [v1.18.0](https://registry.terraform.io/providers/cyrilgdn/postgresql/1.18.0)

**Pull request merged**
