### PR TITLE
Fix building of connection string parameters

### LINKED ISSUE #36: in 1.11.0 sslmode = "disable" does not work properly
I have used latest version 1.11.0 and have issues with 
`pq: SSL is not enabled on the server`
I have downgraded to 1.9.0 and everything work fine

context:

```hcl
terraform {
  required_providers {
    kubernetes = {
      source = "hashicorp/kubernetes"
      version = "1.13.3"
    }
    postgresql = {
      source = "cyrilgdn/postgresql"
      version = "1.9.0"
    }
  }
}

provider "kubernetes" {}

// kubectl port-forward postgres-6b66657994-j2bks 25432:5432
provider "postgresql" {
  host = "127.0.0.1"
  port = "25432"
  database = "postgres"
  username = ******
  password = ******
  sslmode = "disable"
}
```

### PR DESCRIPTION
**Pull request by mcwarman**
Fixes #36

### CODE REVIEW

**Comment by stevehipwell** [comment]
@cyrilgdn could we get this merged and built ASAP.

**Comment by cyrilgdn** [comment]
@mcwarman @stevehipwell Thanks for the PR.

> could we get this merged and built ASAP.

Yes I'll review, merge and release it this evening (CEST time)

**Review by cyrilgdn — APPROVED** [review]
Thanks for the fix (and the associated test :+1: )

I manually tested that certificate work correctly as it was my fear with encode values and it works fine.

**Comment by cyrilgdn** [comment]
@mcwarman @stevehipwell  [v1.11.1](https://registry.terraform.io/providers/cyrilgdn/postgresql/latest) has been released.

**Pull request merged**
