### PR TITLE
feat: bump GoCloud dependency

### PR DESCRIPTION
**Pull request by alethenorio**
Bump gocloud.dev dependency to v0.25.0 with the primary purpose of adding support for workload identity federation

### CODE REVIEW

**Comment by maxekman** [comment]
Any update on this? Seems useful.

**Review by cyrilgdn — APPROVED** [review]
Thanks for these updates :+1:

**Comment by cyrilgdn** [comment]
FYI, this has just been released in [v1.16.0](https://registry.terraform.io/providers/cyrilgdn/postgresql/latest)

**Comment by alethenorio** [comment]
Thank you

**Pull request merged**
