### PR TITLE
create postgres_grant_resource resource

### PR DESCRIPTION
**Pull request by maximilianschelbach**
Creates a resource to it is possible to manage privileges for single resources (like a specific table) not only all resources in the given schema.

### CODE REVIEW

**Comment by maximilianschelbach** [comment]
@cyrilgdn Any updates on this?

**Comment by cyrilgdn** [comment]
@maximilianschelbach Sorry for the response delay, I was a bit off the project for a while.

I'll take a look but after a first very quick look, I already have a couple of questions/remarks:

* Don't you think we could put this `resources` field directly in `postgresql_grant`? And say that it's all the schema resources if this list is empty and the specified ones otherwise.
* What happen (and/or should happen) if you specify several `postgresql_grant_resource` resources for the same `database`/`schema`? I see that the generated resource ID uses the same `generateGrantID` function that `postgresql_grant`. This means that we could have only one `postgresql_grant_resource` per `database`/`schema. Is it on purpose?

**Comment by maximilianschelbach** [comment]
@cyrilgdn I didn't want to change the existing resource, and thought it would kinda overcomplicate the matter.

To the ID, no this was not intended of cause. I just pushed another commit, which added an custom mechanism for that. I do not really know what this ID field is doing (and couldn't find any documentation to that topic), but for me it was working also with the `generateGrantID` function.

**Comment by maximilianschelbach** [comment]
@cyrilgdn Can I expect an answer soon? Otherwise I would going to close this PR and publish my fork on my own into the registry.

**Comment by cyrilgdn** [comment]
@maximilianschelbach 

Yes sorry, I'll take a look tomorrow or this weekend. 

But after a quick look, do you think  it's possible to do it directly in the `postgresql_grant` resource?
A quick diff between `resource_postgresql_grant.go` and `resource_postgresql_grant_resource.go` shows that it's more or less the same base code with the new resource field additions.
Were they some blocking points/difficulties to do it directly in the existing resource? (It was my initial plan)

**Comment by benesch** [comment]
> @maximilianschelbach
> 
> Yes sorry, I'll take a look tomorrow or this weekend.
> 
> But after a quick look, do you think it's possible to do it directly in the `postgresql_grant` resource?
> A quick diff between `resource_postgresql_grant.go` and `resource_postgresql_grant_resource.go` shows that it's more or less the same base code with the new resource field additions.
> Were they some blocking points/difficulties to do it directly in the existing resource? (It was my initial plan)

I also think it'd be preferable to integrate this with the existing resource. I might take a stab at that.

**Comment by benesch** [comment]
Done in #105.

**Comment by cyrilgdn** [comment]
Hi @maximilianschelbach ,

We've just merged #105 that allow to specify objects list directly in the `postgresql_grant` resource.
Would you be able to test it to assert that it works for your use case?

**Comment by maximilianschelbach** [comment]
Hi @cyrilgdn ,

looks like #105 is just another way to do that. So should be totally fine for us. Is there a release date for the provider, so we can migrate to this approach?

**Comment by cyrilgdn** [comment]
@maximilianschelbach I'll create a new release this week-end, I'll let you know here. Thank you for your patience on this subject.

**Pull request closed without merging**
