### PR TITLE
Use gocloud to connect to cloud instances

### PR DESCRIPTION
**Pull request by ademariag**
Implements https://github.com/cyrilgdn/terraform-provider-postgresql/issues/21

### CODE REVIEW

**Review by cyrilgdn — COMMENTED** [review]
@ademariag Thanks for the PR and your work on this.

But as I said in #21, in my mind (and regarding the [GoCloud documentation](https://gocloud.dev/howto/sql/)), it should be more a `scheme` settings which allow to choose which driver to use.

Of course it was not possible in the current state as the current generated DSN uses the key/value connection strings format instead of an URI like GoCloud.

As I always found this function code a bit too blurry for what it does, I took the occasion to rewrite it to use an URI for Postgres and define the `scheme` setting to allow switching the driver to GoCloud.

So I allowed myself to rewrite this PR and created 2 PRs:
* #28 which switches from key/value connection strings to an URI
* #29 which rewrite this PR by creating a new `scheme` setting to switch to GoCloud.

The second one also updates the [documentation](https://github.com/cyrilgdn/terraform-provider-postgresql/blob/gocloud/website/docs/index.html.markdown#gocloud) to explain how to use Gocloud.

Note that I didn't keep the conversion of the GCP connection string and followed the GoCloud format with slashes (`project/region/instance`).
(As I documented it, I don't think it's a big deal if the user has to replace the two points with slashes.)

I created a pre-release version [v1.11.0-pre-gocloud](https://registry.terraform.io/providers/cyrilgdn/postgresql/latest) version if you want to test it (I created instances on AWS & GCP to test it but maybe you have specific setup).

You can use it with:
```
terraform {
  required_version = ">= 0.13"
  required_providers {
    postgresql = {
      source  = "cyrilgdn/postgresql"
      version = "1.11.0-pre-gocloud"
    }
  }
}
```

If you want to review/test these PRs, It'd help a lot :blush:

**Comment by ademariag** [comment]
That's great thank you, your approach seems much cleaner. Will test in the next few days

**Comment by benfdking** [comment]
In terms of testing this. I can't say we've been particularly rigorous ... but it is a pretty straightforward piece of code, if you assume the communication layer to be independent. 

We do use the GCP one in production at Tumelo and have done so for the past few month. We haven't seen any problems apart from the connection fiddles because we pass in variables into the provider. That particular
 connection mechanism to GCP seems to be ok. I would definitely give the AWS one a check even if it is manual ... I can't say I know how to test this more rigorously and continuously though. Happy to help! And if gets merged we will probably migrate to this. As @ademariag is probably very aware, although I may have good intention, I do find it hard to make time. I'd rather be upfront about that.

**Comment by ademariag** [comment]
ok @benfdking thank you. BTW the approach used by @cyrilgdn is different than Tumelo's initial code. 

@cyrilgdn I will probably find time to test this tomorrow. Thank you again

**Comment by cyrilgdn** [comment]
As I said I already tested against a GCP and an AWS instance, so tests on your specific use case only  is already cool :+1: 

A quick review of the code would help too :blush: 

Thanks a lot for your help!

**Comment by ademariag** [comment]
@cyrilgdn perhaps I am not getting something, but before I could use [google_sql_database_instance.antha-database.connection_name](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/sql_database_instance#connection_name ). However now if you expect the `project/region/instance/dbname` format, how do I easily link from an already existing instance?

**Comment by cyrilgdn** [comment]
Replaced by #29

**Pull request closed without merging**
