### PR TITLE
Update Go Build version

### PR DESCRIPTION
**Pull request by benfdking**
- Aligns the test and release go build version
- Allows for building for darwin arm64
- Ran `go mod tidy`

Not sure about process so please let me know if I have done anything wrongly or missed anything.

### CODE REVIEW

**Review by cyrilgdn — APPROVED** [review]
@benfdking Thanks :+1: 

Do you quickly need a release ? Or could we wait to have a couple of of features before releasing it?

**Comment by benfdking** [comment]
Hey @cyrilgdn, if it's not too much of a hassle, I'd be really grateful for a quick release 🙏

**Comment by cyrilgdn** [comment]
@benfdking I'm very sorry I though I triggered the release but I just realized that I forgot apparently....

So I just released [v1.12.1](https://github.com/cyrilgdn/terraform-provider-postgresql/releases/tag/v1.12.1) with the new build version

**Comment by benfdking** [comment]
1. Please don't appologise!
2. Thank you for that and all the amazing work around this package! What a nice surprise for the weekend!

**Pull request merged**
