### PR TITLE
Create temporary file containing Google credentials if `GOOGLE_CREDENTIALS` is provided

### LINKED ISSUE #138: Unable to authenticate with gcppostgres while in Terraform Cloud
Hey there. I'm looking to manage an existing postgres instance that lives in GCP. Everything works fine when I apply changes from a local machine, but I'm running into trouble when applying the same changes via Terraform Cloud. Specifically, running the apply from Terraform Cloud complains because it doesn't have the application default credentials.

The [documentation](https://registry.terraform.io/providers/cyrilgdn/postgresql/latest/docs#gcp) mentions that you need to set the `GOOGLE_APPLICATION_CREDENTIALS` environment variable to be the path to the credentials file. However, to my knowledge,  there's no way to create or store a hard drive file with Terraform Cloud, meaning there's nothing for the `GOOGLE_APPLICATION_CREDENTIALS` to point to.

Are there any known workarounds for situations where you're working on Terraform Cloud or don't have direct hard drive access? Thanks in advance for the help.

### Terraform Version

`v0.14.11`

### Affected Resource(s)

- `postgresql_grant_role`

### Expected Behavior

Running `terraform apply` from Terraform Cloud connects to postgres in GCP.

### Actual Behavior

Running `terraform apply` from Terraform Cloud fails to authenticate with postgres because there's no path to the Google application credentials. (Note that this is only an issue for Terraform Cloud. Everything works fine from a local machine.)

```
Error: Error connecting to PostgreSQL server mygcpproject:myregion:mydbinstance (scheme: gcppostgres): gcppostgres open gcppostgres://terraform:imagineapasswordhere@smygcpproject:myregion:mydbinstance:5432/postgres?fallback_application_name=Terraform+provider: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
```

### Steps to Reproduce

1. Create a postgres instance in GCP.
2. Use the postgres provider to connect to that DB instance. It should work fine on a local machine.
3. Use the same configs on Terraform Cloud. The apply fails because there's no good way to get the application default credentials.

### Important Factoids

Here's a granular list representation of the previously-mentioned context:

* There's a postgres instance that lives in Google Cloud.
* Using the postgres provider works fine on a local machine.
* Using the same Terraform code on Terraform cloud runs into an error due to lack of application default credentials.
* The documentation mentioned setting the `GOOGLE_APPLICATION_CREDENTIALS` environment variable. While it's possible to set the environment variable itself on Terraform Cloud, that variable still needs to point to the credentials json file. There's no way to create that file on Terraform Cloud.

### References

* https://github.com/cyrilgdn/terraform-provider-postgresql/issues/100 may be related. IAM authentication might be a possible fix to this issue.

### PR DESCRIPTION
**Pull request by jeremylvln**
On Terraform Cloud, we do not have access to the file system and thus cannot prepare a credentials file for this provider. The official GCP provider supports the `GOOGLE_CREDENTIALS` environment variable which should contains the JSON key directly.

This PR adds support for this environment variable, will create a temporary file containing the JSON key and will set the `GOOGLE_APPLICATION_CREDENTIALS` to the path of this temporary file.

This work was cherry-picked from @Deiz 's fork repository.

Closes #138

### CODE REVIEW

**Review by cyrilgdn — CHANGES_REQUESTED** [review]
Hi,
Thanks for your work on that and sorry for the late response.

Could you merge master in your branch?

Even if writing credentials in a random file on disk does not seem really good in a security point of view, I'm ok with this workaround, but:
* I'd make it optional with a setting in the provider. Maybe not everyone wants they Google credentials written on the disk if they don't need it.
* Could you document it [here](https://github.com/cyrilgdn/terraform-provider-postgresql/blob/master/website/docs/index.html.markdown#gcp) 
* I'm a bit worried about the fact that these files are not cleanup. I guess in the main purpose, i.e.: Terraform cloud, it's not a problem, but in another context, on every `terraform` command, a new credentials file will be created and never cleaned up (except on computer restart). I don't see any way in the provider SDK to clean up stuff before leaving but if you have an idea?

**Comment by LiuVII** [comment]
hi! any updates here? I have a similar issue with remote execution and have to make a sad hack around with pre-hook/post-hook so it'd be awesome to utilize at least this method

**Comment by kevinjcash** [comment]
I would also love to have this feature. I can try to incorporate the requested changes.

**Comment by cyrilgdn** [comment]
> I would also love to have this feature. I can try to incorporate the requested changes.

@kevinjcash Feel free to do it :+1:

**Pull request closed without merging**
