### PR TITLE
Is community alive?

### PR DESCRIPTION
**Pull request by james64**
Hey,

postgresql terraform provider certainly belongs to those with big potential. Recently its ownership was transferred here to this community project. However
* Issues reporting is disabled
* Website, gitter and mailinglist are not postgresql provider specific but refer to terraform in general
* Creating dummy PR is the only way I can fined to communicate here
* No we-are-working-on-it message of any kind

Without recognition from upstream hashicorp repo this would look just like any other random fork.

So I would like to ask here
* Is the community alive?
* Is an issue tracker going to be enabled?
* Are issues from "old" upstream going to be migrated here (they are very relevant some of them affecting me right now)
* Is a help needed here so that the postgresql provider stays on map an reliable?

I hope you understand my concerns and do not mind reaching out through PR. Thanks

### CODE REVIEW

**Comment by rpf3** [comment]
Would also love to know this as I just got bit by https://github.com/hashicorp/terraform-provider-postgresql/pull/199 not being released yet.

**Comment by cyrilgdn** [comment]
Hi @james64 ,

I enabled the issue trackers.

The migration from terraform-providers to this repo was in progress, normally PRs and issues should have been transferred but it's not the case. I'll check with the Terraform employee that contacted me for that.

There's still a bit of work on my side to update README accordingly though.

> Is a help needed here so that the postgresql provider stays on map an reliable?

Help is always welcome, I'm alone on this (and another provider), so very slow to answer sometime. Every PR, reviews, tests, advice are welcome.

**Comment by cyrilgdn** [comment]
@rpf3 I'll work on next release very soon.

**Comment by cyrilgdn** [comment]
> @rpf3 I'll work on next release very soon.

@rpf3 I released it in 1.8.0 but unfortunately I had to revert it in 1.8.1 as it was not working properly actually.

I've already started to work on a new patch for this in #5 , still a some work to do on it but hopefully, I should be able to validate and release it soon. You can follow the PR or watch in the repository in "Releases" mode to be alerted when it's done.

**Comment by cyrilgdn** [comment]
@james64 I close this PR but feel free to comment it or to open an issue if you want to continue the discussion or if you want to help on some points.

**Pull request closed without merging**
