### PR TITLE
Add SOCKS proxy support

### PR DESCRIPTION
**Pull request by Tenzer**
This copies the implementation from the Redshift provider: https://github.com/brainly/terraform-provider-redshift/pull/19.

It allows users to proxy the requests to the database server through a SOCKS proxy, in case the database server cannot be reached directly.

I have only added it for the "postgres" as it seems to be more cumbersome to do with the AWS and GCP specific drivers, since they wrap the low-level PostgreSQL driver multiple times.

I'd like feedback on if this would be a welcome addition. If so, I'll add some documentation about how to configure this (like the Redshift provider has).

Relates to #184.

### CODE REVIEW

**Comment by aokomorowski** [comment]
I've managed to test your changes in practice. It works according to the instruction from the Redshift provider. Note that the `proxy` package doesn't support `HTTP_PROXY` and `HTTPS_PROXY` like Terraform does, but with `ALL_PROXY` and `NO_PROXY`, it works like a charm 🤌

**Comment by Tenzer** [comment]
For those interested, I have pushed a version of the provider with this patch at https://registry.terraform.io/providers/Tenzer/postgresql/1.15.0-proxy. It should make it easier to test out.

I don't intend to maintain a fork and would instead hope this feature could be incorporated here.

**Review by cyrilgdn — COMMENTED** [review]
Hello,

Thanks for the PR, I allowed myself to merge master as it fixes failing `golangci-lint`.

I don't know by heart the interface for sql/pq but I trust you and the tests :+1: 

Could you just add in the [usage documentation](https://github.com/cyrilgdn/terraform-provider-postgresql/blob/master/website/docs/index.html.markdown) how to use it (more to show that it's possible)?

Thanks in advance.

**Comment by Tenzer** [comment]
@cyrilgdn I've added a couple of lines about it to that document now. I rebased the branch on top of `master` to get the latest fixes in and removed the merge commit.

My workplace has been using this patch since I made the PR, and it's working for us.

**Review by cyrilgdn — APPROVED** [review]

**Comment by cyrilgdn** [comment]
FYI, this has just been released in [v1.16.0](https://registry.terraform.io/providers/cyrilgdn/postgresql/latest)

**Pull request merged**
