### PR TITLE
Fix concurrency issue when granting privileges on databases

### LINKED ISSUE #223: tuple concurrently updated error when granting priviliges on same database for multiple users
### Terraform Version
```
Terraform v1.2.3
on darwin_amd64
+ provider registry.terraform.io/cyrilgdn/postgresql v1.16.0
```

### Affected Resource(s)
- postgresql_grant

### Terraform Configuration Files
```hcl
terraform {
  required_version = ">= 1.0"

  required_providers {
    postgresql = {
      source  = "cyrilgdn/postgresql"
      version = ">=1.16"
    }
  }
}

provider "postgresql" {
  port            = 5432
  database        = "postgres"
  username        = "postgres"
  password        = "password"
  sslmode         = "disable"
  superuser = false
}

resource "postgresql_role" "demo" {
  name     = "demo"
  login    = true
  password = "demo"
}

resource "postgresql_role" "demo2" {
  name     = "demo2"
  login    = true
  password = "demo"
}

resource "postgresql_grant" "demo" {
  database    = "postgres"
  role        = postgresql_role.demo.name
  object_type = "database"
  privileges  = ["CONNECT"]
}

resource "postgresql_grant" "demo2" {
  database    = "postgres"
  role        = postgresql_role.demo2.name
  schema      = "public"
  object_type = "database"
  privileges  = ["CONNECT"]
}
```

### Debug Output
https://gist.github.com/timothegenzmer/c918c3d50acae32c83fade871167d283

### Expected Behavior
The provider is able to grant multiple privileges on the same database for multiple users without error

### Actual Behavior
Postgres error that a tuple is updated concurrently
```
╷
│ Error: could not execute revoke query: pq: tuple concurrently updated
│
│   with postgresql_grant.demo,
│   on main.tf line 45, in resource "postgresql_grant" "demo":
│   45: resource "postgresql_grant" "demo" {
│
╵
```

### Steps to Reproduce
1. `terraform apply`

### References
This seems to be similar to 
https://github.com/cyrilgdn/terraform-provider-postgresql/issues/215
https://github.com/cyrilgdn/terraform-provider-postgresql/issues/178
https://github.com/cyrilgdn/terraform-provider-postgresql/pull/169

### PR DESCRIPTION
**Pull request by timothegenzmer**
This fixes #223

### CODE REVIEW

**Comment by philip-harvey** [comment]
Any news on getting this merged?

**Comment by brokenjacobs** [comment]
@cyrilgdn any chance of this getting merged?

**Comment by BartoszGiza** [comment]
BTW: i think i have workaround for this problem. I have added max_connections = 1 to provider block. Seems to work. Probably it will slow down plans :(

**Comment by seanamos** [comment]
> BTW: i think i have workaround for this problem. I have added max_connections = 1 to provider block. Seems to work. Probably it will slow down plans :(

@BartoszGiza That does work in some cases. Unfortunately that also has another side effect that it can cause the provider to hang indefinitely.

**Comment by BartoszGiza** [comment]
> > BTW: i think i have workaround for this problem. I have added max_connections = 1 to provider block. Seems to work. Probably it will slow down plans :(
> 
> @BartoszGiza That does work in some cases. Unfortunately that also has another side effect that it can cause the provider to hang indefinitely.

Hi, I think i just hit that problem. I have problems with hanging during refreshing states. Also for some reason i can't delete database which provider created.

**Comment by vr** [comment]
Hey @cyrilgdn any updates on this ?

**Review by cyrilgdn — APPROVED** [review]
Hi,

Thanks for your work on that, and sorry for the delay.
I had no time to work on opensource projects these past months...

I haven't test it but code looks good so we can ship it :+1:

**Comment by BartoszGiza** [comment]
@cyrilgdn thank You

**Comment by philip-harvey** [comment]
Will there be a release with this PR included?  Thanks.

**Comment by timothegenzmer** [comment]
Thanks for merging.
We have tested this change in production for a while and it resolved the issue for us without any side effects

**Comment by BartoszGiza** [comment]
@cyrilgdn when do You plan to release new version ?

**Comment by cyrilgdn** [comment]
This has been released in [v1.18.0](https://registry.terraform.io/providers/cyrilgdn/postgresql/1.18.0)

**Comment by philip-harvey** [comment]
I tested 1.18 and am still getting concurrency issues on grants so unfortunately #223  is not fixed

**Comment by timothegenzmer** [comment]
@philip-harvey Are you sure that you are facing the same issue?
This PR only fixes an concurrency issue if you simultaneously grant two different roles privileges on a `database`.
See the example code in the linked issue

**Comment by philip-harvey** [comment]
I am getting errors such as the below when updating grants if I don't have max_connections = 1


│ Error: could not get advisory lock for members of role pdr_ro_rl: pq: deadlock detected
│ 
│   with module.int_pdr.postgresql_grant.objects["b8e4ec3df0d0c7e7d493c4e904bc820e"],
│   on ../../modules/pdr-config/main.tf line 235, in resource "postgresql_grant" "objects":
│  235: resource "postgresql_grant" "objects" {
│ 
╵
╷
│ Error: could not execute revoke query: pq: tuple concurrently updated
│ 
│   with module.int_pdr.postgresql_grant.objects["027c01cac83a9d668d9fe39e210a6278"],
│   on ../../modules/pdr-config/main.tf line 235, in resource "postgresql_grant" "objects":
│  235: resource "postgresql_grant" "objects" {
│ 
╵
╷
│ Error: could not execute revoke query: pq: tuple concurrently updated
│ 
│   with module.int_pdr.postgresql_grant.objects["117188f8b95fd3ede43ec4bc981c8abb"],
│   on ../../modules/pdr-config/main.tf line 235, in resource "postgresql_grant" "objects":
│  235: resource "postgresql_grant" "objects" {
│ 
╵
╷
│ Error: could not execute revoke query: pq: tuple concurrently updated
│ 
│   with module.int_pdr.postgresql_grant.objects["de1c9bcc954536336bb466b2a011beef"],
│   on ../../modules/pdr-config/main.tf line 235, in resource "postgresql_grant" "objects":
│  235: resource "postgresql_grant" "objects" {

**Comment by timothegenzmer** [comment]
Can you provide the relevant terraform code?
Just from the error it is hard to say that you are affected by the same issue, as all are just `postgresql_grant`.

Also the first error: `could not get advisory lock for members of role pdr_ro_rl: pq: deadlock detected` looks worrisome.
Is this a new error since you updated to 1.18?
Could you verify that the same error happened on 1.17.1?

**Comment by philip-harvey** [comment]
This is the specific part of the code that is still failing due to concurrency issues.

`# Grant each role rights to the objects in the schema
resource "postgresql_grant" "objects" {
  for_each    = local.grants_map
  role        = each.value.rolename
  database    = local.database_name
  schema      = each.value.schema
  object_type = each.value.object_type
  objects     = each.value.objects
  privileges  = each.value.privileges
  depends_on = [
    postgresql_role.roles,
    postgresql_schema.schema
  ]
}`

AFAIK this issue has existed on all previous and current versions of the provider and the only known way to work around the issue currently is to set max_connections = 1

**Comment by seanamos** [comment]
I've had to downgrade as this change is causing all sorts of havoc. The biggest one is that its "leaking" advisory locks on databases. I'm often left with multiple locks that I have to manually cleanup.

**Comment by timothegenzmer** [comment]
Hey @seanamos,
Sorry for the late response.

I have tested my code again, but I was not able to leak any locks
I have tested this via `while :; do terraform apply --auto-approve && terraform destroy --auto-approve; done`
and I have checked this with `select relation::regclass, * from pg_locks;`

from what I get `pg_advisory_xact_lock` should not leak any locks when the transaction is not leaked and the transaction should not be leaked as it is released via `defer`

Do you have an example code to reproduce the issue or could you share the leaked locks here so that I can investigate further?

**Comment by timothegenzmer** [comment]
Are you able to provide a terraform configuration that has this issue?
I have tested this again and again with the config I shared in #223 that previously would throw and error and this PR fixed this configuration.

The fix that I provided might have had some side effects that I am not aware of.
I am happy to provide a fix for them if I am able to reproduce the issue

**Comment by pagalba-com** [comment]
I have tested 1.21.1-beta.1 and concurrency issues are not fixed.

The fix provided by giner works. This one not.
Ref: https://github.com/giner/terraform-provider-postgresql/commits/fix_getting_stuck_on_refreshing_postgresql_grant

**Pull request merged**
